export const UI_CONSTANTS = {
  STORAGE_WARNING_THRESHOLD: 80,
  MAX_DUPLICATE_DISPLAY: 3,
  DEBOUNCE_DELAY_MS: 300,
  AUTO_SAVE_DELAY_MS: 1000,
  MAX_RETRY_ATTEMPTS: 3,
  TOAST_DURATION_MS: 3000,
  MODAL_ANIMATION_MS: 200,
  NETWORK_TIMEOUT_MS: 30000,
};

export const LIMITS = {
  MAX_EMPLOYEES: 500,
  MAX_NAME_LENGTH: 100,
  MAX_EMPID_LENGTH: 20,
  MAX_REASON_LENGTH: 500,
  MIN_SEARCH_LENGTH: 2,
};

export const VALIDATION_PATTERNS = {
  EMPLOYEE_ID: /^[A-Z0-9_-]+$/i,
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE: /^[0-9]{10}$/,
};
